// <auto-generated />
using System;
using BuffetDiscovery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuffetDiscovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902204907_AddBookingSystem")]
    partial class AddBookingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.AvailabilityStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OfferingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date", "IsActive");

                    b.HasIndex("OfferingId", "Date")
                        .IsUnique();

                    b.ToTable("AvailabilityStatuses");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmationCode")
                        .IsUnique();

                    b.HasIndex("CustomerPhone");

                    b.HasIndex("OfferingId", "Date", "Status");

                    b.HasIndex("TimeSlotId", "Date", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.BuffetOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("ClosesAt")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("OneOffDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("OpensAt")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,0)");

                    b.Property<DateOnly?>("RamadanEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("RamadanStartDate")
                        .HasColumnType("date");

                    b.Property<int>("Recurrence")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Weekdays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId", "MealType");

                    b.ToTable("Offerings");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.OfferingPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OfferingId");

                    b.ToTable("OfferingPhotos");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("CoverPhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Status");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.RestaurantSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CancellationCutoffMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("FeaturedScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFoundingRestaurant")
                        .HasColumnType("boolean");

                    b.Property<int>("OverbookingTolerancePercent")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferredByRestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("WaitlistOfferWindowMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReferredByRestaurantId");

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("RestaurantSettings");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OfferingId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OfferingId", "IsDeleted");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RestaurantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Waitlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OfferingId")
                        .HasColumnType("integer");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPhone");

                    b.HasIndex("OfferingId", "Date", "Status", "Position");

                    b.HasIndex("TimeSlotId", "Date", "Status", "Position");

                    b.ToTable("WaitlistEntries");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.AvailabilityStatus", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.BuffetOffering", "Offering")
                        .WithMany("AvailabilityStatuses")
                        .HasForeignKey("OfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offering");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.BuffetOffering", "Offering")
                        .WithMany("Bookings")
                        .HasForeignKey("OfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuffetDiscovery.Domain.Entities.TimeSlot", "TimeSlot")
                        .WithMany("Bookings")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Offering");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.BuffetOffering", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany("Offerings")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.OfferingPhoto", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.BuffetOffering", "Offering")
                        .WithMany("Photos")
                        .HasForeignKey("OfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offering");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Restaurant", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.Area", "Area")
                        .WithMany("Restaurants")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.RestaurantSettings", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.Restaurant", "ReferredBy")
                        .WithMany()
                        .HasForeignKey("ReferredByRestaurantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BuffetDiscovery.Domain.Entities.Restaurant", "Restaurant")
                        .WithOne("Settings")
                        .HasForeignKey("BuffetDiscovery.Domain.Entities.RestaurantSettings", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferredBy");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.TimeSlot", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.BuffetOffering", "Offering")
                        .WithMany("TimeSlots")
                        .HasForeignKey("OfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offering");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.User", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany("Users")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Waitlist", b =>
                {
                    b.HasOne("BuffetDiscovery.Domain.Entities.BuffetOffering", "Offering")
                        .WithMany()
                        .HasForeignKey("OfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BuffetDiscovery.Domain.Entities.TimeSlot", "TimeSlot")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Offering");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Area", b =>
                {
                    b.Navigation("Restaurants");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.BuffetOffering", b =>
                {
                    b.Navigation("AvailabilityStatuses");

                    b.Navigation("Bookings");

                    b.Navigation("Photos");

                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.Restaurant", b =>
                {
                    b.Navigation("Offerings");

                    b.Navigation("Settings");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BuffetDiscovery.Domain.Entities.TimeSlot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("WaitlistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
